openapi: 3.0.0
info:
  title: Anthropic Message Batches API
  version: 1.0.0
  description: API for retrieving message batches from Anthropic's language models based on https://docs.anthropic.com/en/api/retrieving-message-batches

servers:
  - url: https://api.anthropic.com/v1

paths:
  /message/batches/{message_batch_id}:
    get:
      summary: Retrieve a message batch
      operationId: getMessageBatch
      tags:
        - MessageBatches
      parameters:
        - in: path
          name: message_batch_id
          required: true
          schema:
            type: string
          description: ID of the Message Batch
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageBatchResponse"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: Your unique API key for authentication
    AnthropicVersionHeader:
      type: apiKey
      in: header
      name: anthropic-version
      description: The version of the Anthropic API you want to use
    AnthropicBetaHeader:
      type: apiKey
      in: header
      name: anthropic-beta
      description: Optional header to specify the beta version(s) you want to use

  schemas:
    MessageBatchResponse:
      type: object
      required:
        - id
        - type
        - status
        - request_counts
        - created_at
        - expires_at
      properties:
        id:
          type: string
          description: Unique object identifier
        type:
          type: string
          enum: [message_batch]
          description: Object type, always "message_batch" for Message Batches
        status:
          type: string
          enum: [in_progress, canceling, ended]
          description: Processing status of the Message Batch
        request_counts:
          $ref: "#/components/schemas/RequestCounts"
        created_at:
          type: string
          format: date-time
          description: RFC 3339 datetime string representing the time at which the Message Batch was created
        expires_at:
          type: string
          format: date-time
          description: RFC 3339 datetime string representing the time at which the Message Batch will expire and end processing, which is 24 hours after creation
        ended_at:
          type: string
          format: date-time
          description: RFC 3339 datetime string representing the time at which processing for the Message Batch ended
        archived_at:
          type: string
          format: date-time
          description: RFC 3339 datetime string representing the time at which the Message Batch was archived and its results became unavailable
        cancellation_initiated_at:
          type: string
          format: date-time
          description: RFC 3339 datetime string representing the time at which cancellation was initiated for the Message Batch
        results_url:
          type: string
          format: uri
          description: URL to a .jsonl file containing the results of the Message Batch requests

    RequestCounts:
      type: object
      properties:
        processing:
          type: integer
        succeeded:
          type: integer
        errored:
          type: integer
        canceled:
          type: integer
        expired:
          type: integer
      description: Tallies requests within the Message Batch, categorized by their status

security:
  - ApiKeyAuth: []
    AnthropicVersionHeader: []
    AnthropicBetaHeader: []
